### ISSUE TITLE
Annoying effects of local docs

### ISSUE THREAD

**Issue by thorwhalen** [i2mint/epythet#12]
The presence of local docs produces a lot of annoying "information washout":

## during IDE (pycharm here) search

When searching for objects, a big proportion of files are html or js, which makes it hard to find stuff.
The cleaner solution would be that I parametrize the search to ignore .js and .html files, but haven't managed to find how to do that.

<img width="370" alt="image" src="https://user-images.githubusercontent.com/1906276/194875147-e9b91177-8510-49f1-980e-23a495e4e024.png">

## in git prints

Hard to see what’s (arguably) more important when, say, doing a git pull.

<img width="894" alt="image" src="https://user-images.githubusercontent.com/1906276/194874421-924417d2-671e-4a73-befe-d16edd751850.png">

# Solution and their tradeoffs

Of course, it's nice to have local documentation, but personally I almost always use online documentation, so it's an easy price for me to pay to not have the docs locally.

What about the solution of putting `docs/*` in the gitignore. Would that be sufficient? in which situations would that **not** be recommended?

**Comment by andeaseme** [comment]
In pycharm, you can exclude search indexing by
`right click folder -> Mark Directory As -> Excluded`

Adding `docs/*` to `.gitignore` is a solution I would go for since docs are compiled and best practice says to not push those to git.  We can create a branch specifically for publishing docs so there would be no reason to see complied docs commited in master branch.

**Comment by thorwhalen** [comment]
A few things about that.

Tasks (assigned to me first and will reassign if I don't get to it):
* add `docs/*` to the default (`wads`) `.gitignore` template
* add `docs/*` to `.gitignore` in all existing projects of i2mint and otosense
* write script to remove all local copies of the `docs/` folder

**Comment by thorwhalen** [comment]
Okay, @andeaseme : I've done the two first ones:
* add `docs/*` to the default (`wads`) `.gitignore` template
* add `docs/*` to `.gitignore` in all existing projects of i2mint and otosense

But trying the third on a single project is not having the effect I want. Not sure if I'm supposed to `rm -rf docs`, or `git rm -r docs` or `git rm -r docs/*` etc. 

I'll let you pick up that one. 

Please have it in the form of a function taking a project root dir (e.g. the `/path/to/epythet` -- **not** `/path/to/epythet/epythet`) and carrying out the work necessary to remove the docs (and not have them come back on the next pull (since the `.gitignore` has `docs/*` now on all our projects).

If you have a local gitignore that ignores gitignore, so don't have the new `docs` ignoring ones I uploaded, you can add the docs/* in your local gitignore files using the `add_docs_to_gitignore` I wrote [here](https://github.com/otosense/installation_scripts/blob/master/installation_scripts/misc/multi_project_action.py). 
Therein you'll find other functions I made that could be useful for this issue.

**Comment by thorwhalen** [comment]
See the (undesirable) effects of my efforts in [mongodol](https://github.com/i2mint/mongodol): I git removed docs folder entirely and pushed that delete. I was hoping that then CI would recreate it from scratch (but not give it to me when I pull). Instead, I just don't have a docs folder at all (though CI is green).

This means that github pages, which points to that docs/ folder, won't see anything there.

**Comment by andeaseme** [comment]
You'll also need the master CI to generate and push new docs to the docs branch

**Comment by thorwhalen** [comment]
Another question (possible task): The `right click folder -> Mark Directory As -> Excluded`. Haven't tried this, so perhaps it works (what I've tried in the past did not). 
But with 100+ otosense+i2mint projects on my side comes the desire to automate that. 

Should be possible by editing the .idea xml for example, but needs to be easy: The buck needs to be low since the bang is (only those, like me, that develop over lots of projects, and use Pycharm). 

I'll have a look.

**Comment by andeaseme** [comment]
New [CI script](https://github.com/i2mint/epythet/blob/61281757e711ee9b40b2a458c4b49016e255f4b6/.github/workflows/ci.yml) removes compiled docs from the master branch.  

Follow up issue created for distributing solution to other repos. https://github.com/i2mint/isee/issues/18
